imports:
    - { resource: tables.yml }
services:
    bruninoit.wvtt.controller:
        class: bruninoit\wvtt\controller\main
        arguments:
            - @auth
            - @controller.helper
            - @dbal.conn
            - @template
            - @user
            - %core.table_prefix%
    bruninoit.wvtt.listener:
        class: bruninoit\wvtt\event\main_listener
        arguments:
            - @auth
            - @content.visibility
            - @controller.helper
            - @dbal.conn
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
        tags:
            - { name: event.listener }
